version: '3'
services:
  app-server:
    build:
      context: .
    volumes:
      - /data/application-server
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/reading-is-good
      - SPRING_DATASOURCE_USERNAME=reading-is-good
      - SPRING_DATASOURCE_PASSWORD=reading-is-good
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: reading-is-good
      POSTGRES_USER: reading-is-good
      POSTGRES_PASSWORD: reading-is-good
    ports:
      - "5432:5432"
