spring:
  liquibase:
    enabled: false
    change-log: "classpath:/scripts/liquibase-changelog.xml"

  sql:
    init:
      platform: postgres
      mode: always
  datasource:
    username: reading-is-good
    password: reading-is-good
    url: jdbc:postgresql://localhost:5432/reading-is-good
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwtSecret: secret
  jwtExpirationMs: 864000

