name: Build

on:
  push:
    branches:
      - post-deadline-fixes

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          cache-to: type=inline
          tags: reading-is-good:latest

      - name: Start Application
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Stop Application
        run: docker-compose -f docker-compose.test.yml down